#pragma once

#define BOOT_SIZE (16 * 1024UL)
#define APP_SIZE (23 * 1024UL)
#define DFU_BAK_SIZE (APP_SIZE)

#define FLASH_START_ADDR (0x8000000)
#define APP_START_ADDR (FLASH_START_ADDR + BOOT_SIZE)
#define DFU_BAK_START_ADDR (APP_START_ADDR + APP_SIZE)

#define APP_INFO_ADDR (DFU_BAK_START_ADDR + APP_SIZE)
#define DFU_FLAG_ADDR (APP_INFO_ADDR + FLASH_PAGE_SIZE)

#define FIWMWARE_INFO_OFFSET (0xc00)
